default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3

test:
  primary:
    <<: *default
    database: storage/test.sqlite3

production:
  primary:
    <<: *default
    database: /data/production_book_club.sqlite3
  cable:
    <<: *default
    database: /data/production_cable.sqlite3
    migrations_paths: db/cable_migrate
