service: book-club

image: tonyyunker/book-club

servers:
  web:
    hosts:
      - 64.225.62.74

registry:
  username: tonyyunker

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RUBY_YJIT_ENABLE: 1
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "data:/data"

proxy:
  ssl: true
  host: 465book.club
  app_port: 3000

builder:
  arch: amd64
